version: "3.1"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: "/home/davgalle/data/wordpress"
      o: bind
 
