
version: "3.1"

networks:
  inception:
    name: inception

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:

  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:

  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
