version: "3.1"

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: "/home/davgalle/data/mariadb"
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: "/home/davgalle/data/wordpress"
      o: bind


