#version: "3.1"

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    expose:
      - "3306"
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    expose:
      - "9000"
      - "3306"
    restart: always

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"
    restart: always

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: "/home/davgalle/data/wordpress"
      o: bind

  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: "/home/davgalle/data/mariadb"
      o: bind
